### Задание 1
Вернемся к набору данных о видеоиграх.

Ответьте на следующие вопросы:

    1. Как критики относятся к спортивным играм?
    2. Критикам нравятся больше игры на PC или на PS4?
    3. Критикам больше нравятся стрелялки или стратегии?

Для каждого вопроса:

- сформулируйте нулевую и альтернативную гипотезы;
- выберите пороговый уровень статистической значимости;
- опишите полученные результаты статистического теста.

In [1]:
import pandas as pd
df = pd.read_csv('vgsales.csv')
df

,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Critic_Score,Critic_Count,User_Score,User_Count,Developer,Rating
0,Wii Sports,Wii,2006.0,Sports,Nintendo,41.36,28.96,3.77,8.45,82.53,76.0,51.0,8,322.0,Nintendo,E
1,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,NaN,NaN,NaN,NaN,NaN,NaN
2,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.68,12.76,3.79,3.29,35.52,82.0,73.0,8.3,709.0,Nintendo,E
3,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.61,10.93,3.28,2.95,32.77,80.0,73.0,8,192.0,Nintendo,E
4,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16714,Samurai Warriors: Sanada Maru,PS3,2016.0,Action,Tecmo Koei,0.00,0.00,0.01,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN
16715,LMA Manager 2007,X360,2006.0,Sports,Codemasters,0.00,0.01,0.00,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN
16716,Haitaka no Psychedelica,PSV,2016.0,Adventure,Idea Factory,0.00,0.00,0.01,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN
16717,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN
16718,Winning Post 8 2016,PSV,2016.0,Simulation,Tecmo Koei,0.00,0.00,0.01,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN

#### 1. Как критики относятся к спортивным играм?
Необходимо определить H0 и H1
Пусть:
- H0 - спортивные игры не нравятся критикам, 
- H1 - спортивные игры нравятся критикам.

Определим пороговое значение, оценка выше которого означает, что игра критику нравится.

In [2]:
[df['Critic_Score'].min(), df['Critic_Score'].mean(), df['Critic_Score'].max()]

[13.0, 68.96767850559173, 98.0]

Минимальная оценка критиков 13, максимальная - 98. Логично предположить, что исходный диапазон оценок - [0, 100].
Примем за пороговое значение 50 баллов. Тогда:
- H0 - спортивные игры не нравятся критикам (Средняя оценка <=50), 
- H1 - спортивные игры нравятся критикам    (Средняя оценка >50).

Здесь, и далее, если не задано иное, примем уровень значимости = 5%

In [3]:
sports = df['Critic_Score'].loc[df['Genre']=='Sports'].dropna()
from scipy import stats as st
alpha = 0.05
threshold = 50
result = st.ttest_1samp(sports, threshold, alternative='greater') # одновыборочный, т.к. сравниваем с константой
print(sports.mean())
print(result)
print('Пороговое значение:', threshold)
print('Уровень значимости:', alpha)
if result.pvalue < alpha:
    print('Спортивные игры нравятся критикам (H1)')
else:
    print('Спортивные игры не нравятся критикам (H0)')

71.96817420435511
Ttest_1sampResult(statistic=54.696017932916575, pvalue=0.0)
Пороговое значение: 50
Уровень значимости: 0.05
Спортивные игры нравятся критикам (H1)

#### Если считать, что оценка выше 50 баллов означает, что игра нравится критику, то при уровне значимости 0.05 можно утверждать, что игры класса Sports нравятся критикам

#### 2. Критикам нравятся больше игры на PC или на PS4?

Нужен двухвыборочный тест.
Примем:
- H0 - Игры на PC и на PS4 критикам нравятся одинаково
- H1 - Предпочтения критиков различаются

In [4]:
pc = df['Critic_Score'].loc[df['Platform']=='PC'].dropna()
ps4 = df['Critic_Score'].loc[df['Platform']=='PS4'].dropna()
result = st.ttest_ind(pc, ps4, equal_var=False) # не знаем, равны ли дисперсии - предполагаем, что не равны
print(result)
if result.pvalue < alpha:
    if result.statistic>0:
        print('PC игры нравятся критикам больше, чем PS4')
    else:
        print('PS4 игры нравятся критикам больше, чем PC')
else:
    print('Игры на платформах PS4 и PC нравятся критикам одинаково (H0)')

Ttest_indResult(statistic=4.3087588262138725, pvalue=2.067249157283479e-05)
PC игры нравятся критикам больше, чем PS4

#### 3. Критикам больше нравятся стрелялки или стратегии?
Нужен двухвыборочный тест. Примем:

- H0 - Стрелялки и стратегии критикам нравятся одинаково
- H1 - Предпочтения критиков различаются

In [5]:
shooter = df['Critic_Score'].loc[df['Genre']=='Shooter'].dropna()
strategy = df['Critic_Score'].loc[df['Genre']=='Strategy'].dropna()
result = st.ttest_ind(shooter, strategy, equal_var=False) # не знаем, равны ли дисперсии - предполагаем, что не равны
print(result)
if result.pvalue < alpha:
    if result.statistic>0:
        print('Стрелялки нравятся критикам больше, чем стратегии')
    else:
        print('Стратегии нравятся критикам больше, чем стрелялки')
else:
    print('Стрелялки и стратегии нравятся критикам одинаково (H0)')

Ttest_indResult(statistic=-2.2972408230640315, pvalue=0.021938989522304823)
Стратегии нравятся критикам больше, чем стрелялки

### Задание 2
Реализуйте базовую модель логистической регрессии для классификации текстовых сообщений (используемые данные здесь) по признаку спама. Для этого:

1. Приведите весь текст к нижнему регистру;
2. Удалите мусорные символы;
3. Удалите стоп-слова;
4. Приведите все слова к нормальной форме;
5. Преобразуйте все сообщения в вектора TF-IDF. Вам поможет следующий код:

        from sklearn.feature_extraction.text import TfidfVectorizer

        tfidf = TfidfVectorizer()
        tfidf_matrix = tfidf.fit_transform(df.Message)
        names = tfidf.get_feature_names()
        tfidf_matrix = pd.DataFrame(tfidf_matrix.toarray(), columns=names)
Можете поэкспериментировать с параметрами TfidfVectorizer;
6. Разделите данные на тестовые и тренировочные в соотношении 30/70, укажите random_state=42. Используйте train_test_split;
7. Постройте модель логистической регрессии, укажите random_state=42, оцените ее точность на тестовых данных;
8. Опишите результаты при помощи confusion_matrix;
9. Постройте датафрейм, который будет содержать все исходные тексты сообщений, классифицированные неправильно (с указанием фактического и предсказанного).

In [6]:
import re
import numpy as np
from nltk.corpus import stopwords
#import nltk
#nltk.download('stopwords')
#nltk.download('wordnet')
from nltk.stem import WordNetLemmatizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
sw_set = set(stopwords.words('english'))
wn_lemmatizer = WordNetLemmatizer()

In [7]:
spam = pd.read_csv('spam.csv')
spam

     Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [8]:
def transform(data):
    # Приводим текст к нижнему регистру, удаляем мусорные символы, перевоим в список
    data = re.sub('[\W_]+',' ', data.lower()).split(' ')
    # Удаляем стоп-слова
    data = [word for word in data if word not in sw_set]
    # Приводим слова к нормальной форме
    data = [wn_lemmatizer.lemmatize(word) for word in data]
    # Склеиваем список слов в строку через пробел
    data = ' '.join(data)
    return data

In [9]:
spam['Message']

0       Go until jurong point, crazy.. Available only ...
1                           Ok lar... Joking wif u oni...
2       Free entry in 2 a wkly comp to win FA Cup fina...
3       U dun say so early hor... U c already then say...
4       Nah I don't think he goes to usf, he lives aro...
                              ...
5567    This is the 2nd time we have tried 2 contact u...
5568                 Will ü b going to esplanade fr home?
5569    Pity, * was in mood for that. So...any other s...
5570    The guy did some bitching but I acted like i'd...
5571                           Rofl. Its true to its name
Name: Message, Length: 5572, dtype: object

In [10]:
spam['Message'].apply(transform)

0       go jurong point crazy available bugis n great ...
1                                ok lar joking wif u oni
2       free entry 2 wkly comp win fa cup final tkts 2...
3                    u dun say early hor u c already say
4                     nah think go usf life around though
                              ...
5567    2nd time tried 2 contact u u 750 pound prize 2...
5568                         ü b going esplanade fr home
5569                                pity mood suggestion
5570    guy bitching acted like interested buying some...
5571                                       rofl true name
Name: Message, Length: 5572, dtype: object

In [11]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer()
tfidf_matrix = tfidf.fit_transform(spam['Message'].apply(transform))
names = tfidf.get_feature_names()
tfidf_matrix = pd.DataFrame(tfidf_matrix.toarray(), columns=names)

In [12]:
tfidf_matrix

,00,000,000pes,008704050406,0089,0121,01223585236,01223585334,0125698789,02,...,zhong,zindgi,zoe,zogtorius,zoom,zouk,zyada,èn,ú1,〨ud
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5567,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5568,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5569,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5570,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5571,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [13]:
# Разбиваем данные на тестовые и тренировочные с заданными параметрами (30/70, random_state=42)
X_train, X_test, y_train, y_test = train_test_split(tfidf_matrix, spam['Category'], test_size=0.3, random_state=42)

In [14]:
# Строим модель
lr = LogisticRegression()
lr.fit(X_train, y_train)

LogisticRegression()

In [15]:
# Точность
accuracy_score(y_test, lr.predict(X_test))

0.958732057416268

In [19]:
C = confusion_matrix(y_test, lr.predict(X_test))

In [20]:
print(f'{C[0,0]} сообщений верно распознаны моделью как "не спам"')
print(f'{C[0,1]} сообщений ошибочно распознаны моделью как "спам"')
print(f'{C[1,0]} сообщений ошибочно распознаны моделью как "не спам"')
print(f'{C[1,1]} сообщений верно распознаны моделью как "спам"')

1445 сообщений верно распознаны моделью как "не спам"
3 сообщений ошибочно распознаны моделью как "спам"
66 сообщений ошибочно распознаны моделью как "не спам"
158 сообщений верно распознаны моделью как "спам"

In [17]:
# результаты предсказания тестовой выборки преобразуем в датафрейм
pred_df = pd.DataFrame(lr.predict(X_test), index=y_test.index, columns=['False Category'])
# оставляем ошибочные предсказания
errors_df = pred_df.join(y_test).loc[pred_df.join(y_test)['False Category']!=pred_df.join(y_test)['Category']]

In [18]:
# Соединяем ошибочные результаты с исходным датафреймом внутренним соединением
result = spam.merge(errors_df['False Category'], how='inner', left_index=True, right_index=True)
result

,Category,Message,False Category
15,spam,"XXXMobileMovieClub: To use your credit, click ...",ham
19,spam,England v Macedonia - dont miss the goals/team...,ham
68,spam,"Did you hear about the new ""Divorce Barbie""? I...",ham
95,spam,Your free ringtone is waiting to be collected....,ham
135,spam,Want 2 get laid tonight? Want real Dogging loc...,ham
...,...,...,...
4652,spam,A £400 XMAS REWARD IS WAITING FOR YOU! Our com...,ham
5037,spam,You won't believe it but it's true. It's Incre...,ham
5120,spam,PRIVATE! Your 2003 Account Statement for 078,ham
5366,spam,A £400 XMAS REWARD IS WAITING FOR YOU! Our com...,ham
5377,spam,The current leading bid is 151. To pause this ...,ham